title: Techempower benchmarks conclusion
description: Overview of all benchmarks from techempower.com
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
theme: jekyll-theme-cayman